[[library]]
type="file"
name="uxplay"
path="UxPlay/lib"
includes=["raop.h"]
incdir="../lib"

[[library]]
type="file"
name="llhttp"
path="UxPlay/lib/llhttp"
includes=["llhttp/llhttp.h"]

[[library]]
type="file"
name="playfair"
path="UxPlay/lib/playfair"
includes=["playfair/playfair.h"]
